### ISSUE TITLE
any provision to i18n?

### ISSUE THREAD

**Issue by irbian** [jsonstat/jsonstat#4]

**Comment by badosa** [comment]
No description provided. The issue does not specify what is not i18n in JSON-stat.

**Comment by irbian** [comment]
Let's pick this first example from here https://json-stat.org/schema/

```
{
   "version" : "2.0",
   "class" : "dataset",
   "label" : "Population in Tuvalu in 2002. By sex",
   "value" : [4729, 4832, 9561],
   "id" : ["metric", "time", "geo", "sex"],
   "size" : [1, 1, 1, 3],
   "dimension" : {
      "sex" : {
         "label" : "sex",
         "category" : {
            "index" : {
              "M" : 0,
              "F" : 1,
              "T" : 2
            },
            "label" : {
              "M" : "men",
              "F" : "women",
              "T" : "total"
            }
         }
      }
   }
}
```

First, what metadata says that this data labels are in english?
Second, any way that allow me to provide labels in multiple languages? Here https://json-stat.org/format/#label in label, it says is "language-dependent"

**Comment by badosa** [comment]
@irbian Thanks for your clarification. 

If, for some reason you need to specify the language of the response, as in many JSON REST APIs, it is assumed that you will use a HTTP header to provide such information (typically, the Content-Language header, even though, as per specification, it is not exactly the same thing as the response language, but the practical difference is negligible).

Because in JSON-stat metadata and data are strictly separated and JSON-stat supports dimension responses and even metadata-only dataset responses, JSON-stat does not offer a way to support several languages in the same response: instead, it is assumed that, if a provider, for some reason, wants to minimize at all cost the number of data transfers, it can use non-data requests to get the info in a different language.
